name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        dotnet: [6.0.401]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install local tools
      run: dotnet tool restore

    - name: Paket Restore
      run: dotnet paket restore

    - name: Build
      run: dotnet build ./src/

    - name: Test
      run: dotnet test ./src/