name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install local tools
      run: dotnet tool restore

    - name: Paket Restore
      run: dotnet paket restore

    - name: Build
      run: dotnet build ./src/

    - name: Test
      run: dotnet test ./src/